Repository openservicemesh/osm, pull requests merged in 2021-09, with the labels that each got.

#4074 pkg/*: address control plane implementation gaps
  pkg/catalog/inbound_traffic_policies.go
  pkg/catalog/inbound_traffic_policies_test.go
  pkg/catalog/ingress.go
  pkg/catalog/ingress_test.go
  pkg/catalog/mock_catalog_generated.go
  pkg/catalog/outbound_traffic_policies.go
  pkg/catalog/outbound_traffic_policies_test.go
  pkg/catalog/service.go
  pkg/catalog/service_test.go
  pkg/catalog/types.go
  pkg/envoy/cds/cluster.go
  pkg/envoy/cds/cluster_test.go
  pkg/envoy/cds/response.go
  pkg/envoy/cds/response_test.go
  pkg/envoy/eds/cluster_load_assignment.go
  pkg/envoy/eds/cluster_load_assignment_test.go
  pkg/envoy/eds/response.go
  pkg/envoy/eds/response_test.go
  pkg/envoy/lds/inmesh.go
  pkg/envoy/lds/inmesh_test.go
  pkg/envoy/lds/listener.go
  pkg/envoy/lds/response_test.go
  pkg/envoy/rds/response.go
  pkg/envoy/rds/response_test.go
  pkg/envoy/rds/route/route_config.go
  pkg/envoy/rds/route/route_config_test.go
  pkg/envoy/registry/services.go
  pkg/envoy/registry/services_test.go
  pkg/envoy/types.go
  pkg/envoy/xdsutil.go
  pkg/envoy/xdsutil_test.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mock_controller_generated.go
  pkg/k8s/types.go
  pkg/k8s/util.go
  pkg/k8s/util_test.go
  pkg/providers/kube/client.go
  pkg/providers/kube/client_test.go
  pkg/providers/kube/fake.go
  pkg/service/mock_service_provider_generated.go
  pkg/service/types.go
  pkg/service/types_test.go
  pkg/tests/fixtures.go
  pkg/trafficpolicy/egress_types.go
  pkg/trafficpolicy/trafficpolicy.go
  pkg/trafficpolicy/trafficpolicy_test.go
  pkg/trafficpolicy/types.go
  pkg/utils/service.go
  pkg/utils/service_test.go
  tests/e2e/e2e_multiple_ports_per_service_test.go
  tests/e2e/e2e_trafficsplit_recursive_split.go
  tests/e2e/e2e_trafficsplit_test.go
  tests/framework/common.go
  tests/scenarios/helpers.go
  tests/scenarios/traffic_split_with_apex_service_test.go
  tests/scenarios/traffic_split_with_zero_weight_test.go
Labels: release/v1

#4084 charts/osm: add namespace to preset-mesh-config resource
  charts/osm/templates/preset-mesh-config.yaml
Labels: backport-to/release=v0.10

#3921 feat(windows): Adds demo containers based on Windows
  Makefile
  demo/run-osm-demo.sh
  demo/run-osm-multicluster-demo.sh
  dockerfiles/Dockerfile.bookbuyer.windows
  dockerfiles/Dockerfile.bookstore.windows
  dockerfiles/Dockerfile.bookthief.windows
  dockerfiles/Dockerfile.bookwarehouse.windows
  dockerfiles/Dockerfile.tcp-client.windows
  dockerfiles/Dockerfile.tcp-echo-server.windows
  scripts/publish-image.sh
Labels: area/windows

#4114 chore(*): update osm install demo
  README.md
  img/osm-install-demo-v0.2.0.gif
  img/osm-install-demo-v0.9.2.gif
Labels: automerge

#4138 fix(healthcheck): set curl connect timeout
  charts/osm/templates/osm-deployment.yaml
  charts/osm/templates/osm-injector-deployment.yaml
Labels: backport-to/release=v0.10

#4140 fix(charts/osm/templates): fixes syntax for tracingAddress
  charts/osm/templates/preset-mesh-config.yaml
Labels: automerge
