Repository openservicemesh/osm, pull requests merged in 2021-07, with the labels that each got.

#3692 feat(pkg/envoy/lds): Switch the gateway listener to proxy mode
  pkg/envoy/lds/gateway.go
  pkg/envoy/lds/gateway_test.go
  pkg/envoy/lds/inmesh.go
  pkg/envoy/lds/inmesh_test.go
  pkg/envoy/lds/response_test.go
  pkg/service/service.go
  pkg/service/service_test.go
Labels: area/multicluster

#3620 feat(provider): catalog uses service and endpoint providers methods
  DESIGN.md
  cmd/osm-controller/osm-controller.go
  pkg/catalog/catalog.go
  pkg/catalog/endpoint_test.go
  pkg/catalog/errors.go
  pkg/catalog/fake.go
  pkg/catalog/helpers_test.go
  pkg/catalog/inbound_traffic_policies_test.go
  pkg/catalog/outbound_traffic_policies.go
  pkg/catalog/outbound_traffic_policies_test.go
  pkg/catalog/service.go
  pkg/catalog/service_test.go
  pkg/catalog/traffictarget.go
  pkg/endpoint/mock_endpoint_provider_generated.go
  pkg/endpoint/types.go
  pkg/providers/kube/client.go
  pkg/providers/kube/client_test.go
  pkg/providers/kube/fake.go
  pkg/service/mock_service_provider_generated.go
  pkg/service/types.go
  pkg/tests/fixtures.go
  tests/scenarios/traffic_split_with_apex_service_test.go
Labels: area/multicluster

#3721 feat(multicluster): kube provider support multicluster
  charts/osm/crds/multiclusterservice.yaml
  pkg/config/client.go
  pkg/config/mock_client_generated.go
  pkg/config/types.go
  pkg/providers/kube/client.go
  pkg/providers/kube/client_test.go
  pkg/providers/kube/types.go
Labels: area/multicluster

#3737 test(pipelines): fix noinstall nightly
  .github/workflows/nightly-noinstall.yml
Labels: do-not-merge/hold

#3869 go/deps: update Helm to v3.6.1, client-go & controller-runtime
  codegen/gen-crd-client.sh
  go.mod
  go.sum
  pkg/k8s/portforward_test.go
  pkg/reconciler/reconciler.go
  tests/scenarios/scenario_mutatingwebhook_reconcile_test.go
Labels: dependencies
