Repository openservicemesh/osm, pull requests merged in 2021-08, with the labels that each got.

#3965 fix(cli): fix proxy get command truncating output
  cmd/cli/proxy_get.go
Labels: automerge

#3685 feat(multicluster): add weight to RemoteCluster
  charts/osm/crds/config_multicluster_service.yaml
  pkg/apis/config/v1alpha1/multi_cluster_service.go
Labels: area/multicluster

#4007 ingress: don't error if candidate group version is not available
  pkg/errcode/errcode.go
  pkg/ingress/client.go
  pkg/ingress/client_test.go
Labels: bug-fix/backport-to=v0.9

#4015 test(pkg/certificate/providers): add tests to config file
  pkg/certificate/providers/config_test.go
Labels: automerge
