Repository openservicemesh/osm, pull requests merged in 2021-04, with the labels that each got.

#3025 test(pkg/envoy/ads): Add test for Server.GetXDSLog()
  pkg/envoy/ads/debugger_test.go
Labels: automerge

#3088 style(pkg/trafficpolicy/trafficpolicy_test): Alias deckarep/golang-set with mapset
  pkg/trafficpolicy/trafficpolicy_test.go
Labels: autorebase

#3089 style(pkg/trafficpolicy): Convert to mapset
  pkg/trafficpolicy/trafficpolicy.go
  pkg/trafficpolicy/types.go
Labels: automerge

#3087 style(pkg/envoy/route/route_config_test): Alias deckarep/golang-set with mapset
  pkg/envoy/route/route_config_test.go
Labels: automerge

#3027 test(pkg/envoy): add test for getFileAccessLog()
  pkg/envoy/xdsutil_test.go
Labels: automerge

#3086 style(pkg/envoy/route/rbac_test): Alias deckarep/golang-set with mapset
  pkg/envoy/route/rbac_test.go
Labels: automerge

#3085 style(pkg/envoy/route/route_config): Alias deckarep/golang-set with mapset
  pkg/envoy/route/route_config.go
Labels: automerge, autorebase

#3108 feat(osm/Chart.yaml): Pre-install check for k8s version
  charts/osm/Chart.yaml
  tests/e2e/e2e_k8s_version_test.go
Labels: automerge, autorebase

#3121 docs(ingress): Add Azure Application Gateway ingress demo
  docs/content/docs/tasks_usage/traffic_management/demos/azure_application_gateway_ingress_demo.md
  docs/content/docs/tasks_usage/traffic_management/ingress.md
Labels: autorebase

#3115 catalog: Remove GetServicesForServiceAccount from MeshCataloger interface
  pkg/catalog/mock_catalog_generated.go
  pkg/catalog/outbound_traffic_policies.go
  pkg/catalog/service.go
  pkg/catalog/types.go
Labels: do-not-merge/hold

#3167 docs(ingress): Gloo Edge Ingress Demo
  docs/content/docs/tasks_usage/traffic_management/demos/gloo_edge_ingress_demo.md
  docs/content/docs/tasks_usage/traffic_management/ingress.md
Labels: autorebase

#3146 update envoy to 1.17.2
  charts/osm/README.md
  charts/osm/values.schema.json
  charts/osm/values.yaml
  docs/content/docs/application_health_probes.md
  docs/content/docs/control_plane_health_probes.md
  docs/content/docs/tasks_usage/metrics.md
  docs/content/docs/troubleshooting/observability/prometheus.md
Labels: automerge

#3257 ref(catalog): remove GetMeshSpec from MeshCataloger
  pkg/catalog/catalog.go
  pkg/catalog/catalog_test.go
  pkg/catalog/mock_catalog_generated.go
  pkg/catalog/outbound_traffic_policies.go
  pkg/catalog/outbound_traffic_policies_test.go
  pkg/catalog/types.go
  pkg/envoy/lds/inmesh.go
  pkg/envoy/lds/inmesh_test.go
Labels: automerge

#3238 fix(maestro): timeout when no logs are written
  ci/cmd/maestro/kubernetes_tools.go
Labels: automerge
