Repository openservicemesh/osm, pull requests merged in 2021-03, with the labels that each got.

#2739 Fixing links
  docs/content/docs/install/uninstallation_guide.md
  docs/content/docs/troubleshooting/uninstall/_index.md
Labels: documentation

#2745 Typo correction
  DESIGN.md
  docs/content/docs/design_concepts/_index.md
Labels: documentation

#2778 tests(pkg/cli): add test for EnvVars()
  pkg/cli/environment_test.go
Labels: cherry-pick to v0.8.0

#2784 docs(install): Document how to install on OpenShift
  demo/README.md
  demo/run-osm-demo.sh
  docs/content/docs/install/_index.md
  docs/content/docs/install/manual_demo/_index.md
Labels: cherry-pick to v0.8.0

#2814 fix(e2e): fix HTTP ingress test when OSM is installed outside osm-system
  tests/e2e/e2e_http_ingress_test.go
Labels: cherry-pick to v0.8.0

#2809 fix(*): rm filterTrafficSplit logic as it is no longer needed
  pkg/catalog/xds_certificates.go
  pkg/catalog/xds_certificates_test.go
  tests/e2e/e2e_trafficsplit_recursive_split.go
Labels: cherry-pick to v0.8.0

#2843 Move e2e log level to trace
  tests/framework/common.go
Labels: automerge

#2896 fix(e2e): fix HTTP ingress e2e on non-kind
  tests/e2e/e2e_http_ingress_test.go
Labels: needs-cherry-pick-v0.8.0

#2907 doc: Adding a new simple demo - first steps
  docs/demos/first_steps.md
Labels: needs-cherry-pick-v0.8.0

#2929 ref(*): update osm namespace add description
  cmd/cli/namespace_add.go
Labels: automerge

#2963 fix(ci): fix missing paren
  .github/workflows/main.yml
Labels: automerge

#2977 test(pkg/envoy): add test for UnmarshalSDSCert
  pkg/envoy/xdsutil_test.go
Labels: automerge

#2987 test(pkg/envoy): add test for pbStringValue()
  pkg/envoy/xdsutil_test.go
Labels: automerge-squash

#3028 test(pkg/envoy/ads): add test to Liveness() and Readiness()
  pkg/envoy/ads/health_test.go
Labels: automerge

#3052 bug(reconciler): fix name of mutating webhook in reconciler
  cmd/osm-injector/reconcile.go
Labels: automerge
