Repository openservicemesh/osm, pull requests merged in 2022-01, with the labels that each got.

#4431 [reconciler]: fix label assignment on mwhc
  pkg/injector/webhook.go
Labels: backport-to/release=v1.0.0

#4433 fix(cli): do not throw error for osm version when no control plane found
  cmd/cli/version.go
  cmd/cli/version_test.go
Labels: backport-to/release=v1.0.0

#4454 fix(grafana): remove hardcoded control plane namespace
  charts/osm/grafana/dashboards/osm-mesh-envoy-details.json
  charts/osm/templates/grafana-configmap.yaml
Labels: blocker/release=v1.0.0

#4487 chore(pkg/catalog): Remove unused variable
  pkg/catalog/inbound_traffic_policies.go
Labels: automerge
